_CONVERSION(`GtkSourceLanguage*',`Glib::RefPtr<SourceLanguage>',`Glib::wrap($3)')
_CONVERSION(`GtkSourceLanguage*',`Glib::RefPtr<const SourceLanguage>',`Glib::wrap($3)')
#_CONVERSION(`Glib::RefPtr<SourceLanguage>',`GtkSourceLanguage*',__CONVERT_REFPTR_TO_P)
_CONVERSION(`const Glib::SListHandle<Glib::ustring>&', `GSList*',`$3.data()')
_CONVERSION(`GtkSourceMarker*',`Glib::RefPtr<SourceMarker>',`Glib::wrap($3)')
_CONVERSION(`GtkSourceMarker*',`Glib::RefPtr<const SourceMarker>',`Glib::wrap($3)')
#_CONVERSION(`Glib::RefPtr<SourceMarker>',`GtkSourceMarker*',__CONVERT_REFPTR_TO_P)
_CONVERSION(`GSList*', `Glib::SListHandle<Glib::RefPtr<SourceMarker> >', `$2($3, Glib::OWNERSHIP_DEEP)')
