// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GTKSOURCEVIEWMM_SOURCETAGSTYLE_P_H
#define _GTKSOURCEVIEWMM_SOURCETAGSTYLE_P_H
#include <gdkmm/private/color_p.h>
#endif /* _GTKSOURCEVIEWMM_SOURCETAGSTYLE_P_H */

