// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GTKSOURCEVIEWMM_SOURCETAG_P_H
#define _GTKSOURCEVIEWMM_SOURCETAG_P_H
#include <gtkmm/private/object_p.h>

#include <glibmm/class.h>

namespace gtksourceview
{

class SourceTag_Class : public Glib::Class
{
public:
#ifndef DOXYGEN_SHOULD_SKIP_THIS
  typedef SourceTag CppObjectType;
  typedef GtkSourceTag BaseObjectType;
  typedef GtkSourceTagClass BaseClassType;
  typedef Gtk::TextTag_Class CppClassParent;
  typedef GtkTextTagClass BaseClassParent;

  friend class SourceTag;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */

  const Glib::Class& init();

  static void class_init_function(void* g_class, void* class_data);

  static Glib::ObjectBase* wrap_new(GObject*);

protected:

  //Callbacks (default signal handlers):
  //These will call the *_impl member methods, which will then call the existing default signal callbacks, if any.
  //You could prevent the original default signal handlers being called by overriding the *_impl method.

  //Callbacks (virtual functions):
};


} // namespace gtksourceview

#endif /* _GTKSOURCEVIEWMM_SOURCETAG_P_H */

