// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GTKSOURCEVIEWMM_SOURCEMARKER_P_H
#define _GTKSOURCEVIEWMM_SOURCEMARKER_P_H
#include <gtkmm/private/textmark_p.h>
#endif /* _GTKSOURCEVIEWMM_SOURCEMARKER_P_H */

