// Generated by gtkmmproc -- DO NOT MODIFY!


#include <gtksourceviewmm/sourceview.h>
#include <gtksourceviewmm/private/sourceview_p.h>

/* GtkSourceView::SourceView
 *
 * Copyright 2004-2005 Jae Jang
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */
#include <gtksourceviewmm/sourceview.h>
#include <gtksourceview/gtksourceview.h>
#include <gtksourceview/gtksourceview-typebuiltins.h>

namespace gtksourceview
{

SourceView::SourceView() :
    Glib::ObjectBase(0), //Mark this class as gtkmmproc-generated, rather than a custom class, to allow vfunc optimisations.
  Gtk::TextView(Glib::ConstructParams(sourceview_class_.init(), (char*) 0))
{
    GtkSourceBuffer *buffer = gtk_source_buffer_new (NULL) ;
    gtk_text_view_set_buffer (GTK_TEXT_VIEW (gobject_), GTK_TEXT_BUFFER (buffer));
}

SourceView::SourceView(Glib::RefPtr<SourceBuffer> &a_buffer) :
    Glib::ObjectBase(0), //Mark this class as gtkmmproc-generated, rather than a custom class, to allow vfunc optimisations.
  Gtk::TextView(Glib::ConstructParams(sourceview_class_.init(), (char*) 0))
{
    if (a_buffer) {
        set_buffer (a_buffer) ;
    } else {
        gtk_text_view_set_buffer (GTK_TEXT_VIEW (gobject_), NULL) ;
    }
}

Glib::RefPtr<const SourceBuffer>
SourceView::get_source_buffer () const
{
    Glib::RefPtr<SourceBuffer> buffer ;
    if (!get_buffer ()) {
        return buffer ;
    }
    buffer = Glib::wrap (GTK_SOURCE_BUFFER (get_buffer ()->gobj ()), true);
    return buffer ;
}

Glib::RefPtr<SourceBuffer>
SourceView::get_source_buffer ()
{
    Glib::RefPtr<SourceBuffer> buffer ;
    if (!get_buffer ()) {
        return buffer ;
    }
    buffer = Glib::wrap (GTK_SOURCE_BUFFER (get_buffer ()->gobj ()), true) ;
    return buffer ;

}

void
SourceView::set_source_buffer (Glib::RefPtr<SourceBuffer> &source_buffer)
{
    set_buffer (source_buffer) ;
}

}//end namespace gtksourceview


namespace
{

static const Glib::SignalProxyInfo SourceView_signal_redo_info =
{
  "redo",
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback,
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback
};


static const Glib::SignalProxyInfo SourceView_signal_undo_info =
{
  "undo",
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback,
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback
};

} // anonymous namespace


namespace Glib
{

gtksourceview::SourceView* wrap(GtkSourceView* object, bool take_copy)
{
  return dynamic_cast<gtksourceview::SourceView *> (Glib::wrap_auto ((GObject*)(object), take_copy));
}

} /* namespace Glib */

namespace gtksourceview
{


/* The *_Class implementation: */

const Glib::Class& SourceView_Class::init()
{
  if(!gtype_) // create the GType if necessary
  {
    // Glib::Class has to know the class init function to clone custom types.
    class_init_func_ = &SourceView_Class::class_init_function;

    // This is actually just optimized away, apparently with no harm.
    // Make sure that the parent type has been created.
    //CppClassParent::CppObjectType::get_type();

    // Create the wrapper type, with the same class/instance size as the base type.
    register_derived_type(gtk_source_view_get_type());

    // Add derived versions of interfaces, if the C type implements any interfaces:
  }

  return *this;
}

void SourceView_Class::class_init_function(void* g_class, void* class_data)
{
  BaseClassType *const klass = static_cast<BaseClassType*>(g_class);
  CppClassParent::class_init_function(klass, class_data);

#ifdef GLIBMM_VFUNCS_ENABLED
#endif //GLIBMM_VFUNCS_ENABLED
  klass->redo = &redo_callback;
  klass->undo = &undo_callback;
}

#ifdef GLIBMM_VFUNCS_ENABLED
#endif //GLIBMM_VFUNCS_ENABLED

void SourceView_Class::redo_callback(GtkSourceView* self)
{
  CppObjectType *const obj = dynamic_cast<CppObjectType*>(
      Glib::ObjectBase::_get_current_wrapper((GObject*)self));

  // Non-gtkmmproc-generated custom classes implicitly call the default
  // Glib::ObjectBase constructor, which sets is_derived_. But gtkmmproc-
  // generated classes can use this optimisation, which avoids the unnecessary
  // parameter conversions if there is no possibility of the virtual function
  // being overridden:
  if(obj && obj->is_derived_())
  {
    #ifdef GLIBMM_EXCEPTIONS_ENABLED
    try // Trap C++ exceptions which would normally be lost because this is a C callback.
    {
    #endif //GLIBMM_EXCEPTIONS_ENABLED
      // Call the virtual member method, which derived classes might override.
      obj->on_redo();
    #ifdef GLIBMM_EXCEPTIONS_ENABLED
    }
    catch(...)
    {
      Glib::exception_handlers_invoke();
    }
    #endif //GLIBMM_EXCEPTIONS_ENABLED
  }
  else
  {
    BaseClassType *const base = static_cast<BaseClassType*>(
        g_type_class_peek_parent(G_OBJECT_GET_CLASS(self)) // Get the parent class of the object class (The original underlying C class).
    );

    // Call the original underlying C function:
    if(base && base->redo)
      (*base->redo)(self);
  }
}

void SourceView_Class::undo_callback(GtkSourceView* self)
{
  CppObjectType *const obj = dynamic_cast<CppObjectType*>(
      Glib::ObjectBase::_get_current_wrapper((GObject*)self));

  // Non-gtkmmproc-generated custom classes implicitly call the default
  // Glib::ObjectBase constructor, which sets is_derived_. But gtkmmproc-
  // generated classes can use this optimisation, which avoids the unnecessary
  // parameter conversions if there is no possibility of the virtual function
  // being overridden:
  if(obj && obj->is_derived_())
  {
    #ifdef GLIBMM_EXCEPTIONS_ENABLED
    try // Trap C++ exceptions which would normally be lost because this is a C callback.
    {
    #endif //GLIBMM_EXCEPTIONS_ENABLED
      // Call the virtual member method, which derived classes might override.
      obj->on_undo();
    #ifdef GLIBMM_EXCEPTIONS_ENABLED
    }
    catch(...)
    {
      Glib::exception_handlers_invoke();
    }
    #endif //GLIBMM_EXCEPTIONS_ENABLED
  }
  else
  {
    BaseClassType *const base = static_cast<BaseClassType*>(
        g_type_class_peek_parent(G_OBJECT_GET_CLASS(self)) // Get the parent class of the object class (The original underlying C class).
    );

    // Call the original underlying C function:
    if(base && base->undo)
      (*base->undo)(self);
  }
}


Glib::ObjectBase* SourceView_Class::wrap_new(GObject* o)
{
  return manage(new SourceView((GtkSourceView*)(o)));

}


/* The implementation: */

SourceView::SourceView(const Glib::ConstructParams& construct_params)
:
  Gtk::TextView(construct_params)
{
  }

SourceView::SourceView(GtkSourceView* castitem)
:
  Gtk::TextView((GtkTextView*)(castitem))
{
  }

SourceView::~SourceView()
{
  destroy_();
}

SourceView::CppClassType SourceView::sourceview_class_; // initialize static member

GType SourceView::get_type()
{
  return sourceview_class_.init().get_type();
}

GType SourceView::get_base_type()
{
  return gtk_source_view_get_type();
}


Glib::RefPtr<SourceView> SourceView::create()
{
  return Glib::RefPtr<SourceView>( new SourceView() );
}
Glib::RefPtr<SourceView> SourceView::create(Glib::RefPtr<SourceBuffer> & buffer)
{
  return Glib::RefPtr<SourceView>( new SourceView(buffer) );
}
void SourceView::set_show_line_numbers(bool show)
{
gtk_source_view_set_show_line_numbers(gobj(), static_cast<int>(show)); 
}

bool SourceView::get_show_line_numbers()
{
  return gtk_source_view_get_show_line_numbers(gobj());
}

void SourceView::set_show_line_markers(bool show)
{
gtk_source_view_set_show_line_markers(gobj(), static_cast<int>(show)); 
}

bool SourceView::get_show_line_markers()
{
  return gtk_source_view_get_show_line_markers(gobj());
}

void SourceView::set_tabs_width(guint width)
{
gtk_source_view_set_tabs_width(gobj(), width); 
}

guint SourceView::get_tabs_width()
{
  return gtk_source_view_get_tabs_width(gobj());
}

void SourceView::set_auto_indent(bool enable)
{
gtk_source_view_set_auto_indent(gobj(), static_cast<int>(enable)); 
}

bool SourceView::get_auto_indent()
{
  return gtk_source_view_get_auto_indent(gobj());
}

void SourceView::set_insert_spaces_instead_of_tabs(bool enable)
{
gtk_source_view_set_insert_spaces_instead_of_tabs(gobj(), static_cast<int>(enable)); 
}

bool SourceView::get_insert_spaces_instead_of_tabs()
{
  return gtk_source_view_get_insert_spaces_instead_of_tabs(gobj());
}

void SourceView::set_show_margin(bool show)
{
gtk_source_view_set_show_margin(gobj(), static_cast<int>(show)); 
}

bool SourceView::get_show_margin()
{
  return gtk_source_view_get_show_margin(gobj());
}

void SourceView::set_highlight_current_line(bool highlight)
{
gtk_source_view_set_highlight_current_line(gobj(), static_cast<int>(highlight)); 
}

bool SourceView::get_highlight_current_line()
{
  return gtk_source_view_get_highlight_current_line(gobj());
}

void SourceView::set_margin(guint margin)
{
gtk_source_view_set_margin(gobj(), margin); 
}

guint SourceView::get_margin()
{
  return gtk_source_view_get_margin(gobj());
}

void SourceView::set_marker_pixbuf(const Glib::ustring& marker, Glib::RefPtr<Gdk::Pixbuf> pixbuf)
{
gtk_source_view_set_marker_pixbuf(gobj(), marker.c_str(), Glib::unwrap(pixbuf)); 
}

Glib::RefPtr<Gdk::Pixbuf> SourceView::get_marker_pixbuf(const Glib::ustring& marker)
{
  return Glib::wrap(gtk_source_view_get_marker_pixbuf(gobj(), marker.c_str()));
}

void SourceView::set_smart_home_end(bool enable)
{
gtk_source_view_set_smart_home_end(gobj(), static_cast<int>(enable)); 
}

bool SourceView::get_smart_home_end()
{
  return gtk_source_view_get_smart_home_end(gobj());
}


Glib::SignalProxy0< void > SourceView::signal_redo()
{
  return Glib::SignalProxy0< void >(this, &SourceView_signal_redo_info);
}

Glib::SignalProxy0< void > SourceView::signal_undo()
{
  return Glib::SignalProxy0< void >(this, &SourceView_signal_undo_info);
}


void gtksourceview::SourceView::on_redo()
{
  BaseClassType *const base = static_cast<BaseClassType*>(
      g_type_class_peek_parent(G_OBJECT_GET_CLASS(gobject_)) // Get the parent class of the object class (The original underlying C class).
  );

  if(base && base->redo)
    (*base->redo)(gobj());
}

void gtksourceview::SourceView::on_undo()
{
  BaseClassType *const base = static_cast<BaseClassType*>(
      g_type_class_peek_parent(G_OBJECT_GET_CLASS(gobject_)) // Get the parent class of the object class (The original underlying C class).
  );

  if(base && base->undo)
    (*base->undo)(gobj());
}


#ifdef GLIBMM_VFUNCS_ENABLED
#endif //GLIBMM_VFUNCS_ENABLED


} // namespace gtksourceview


